export const CH = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  worktreesList: 'worktrees:list',
  worktreesCommits: 'worktrees:commits',
  worktreesCommitDiff: 'worktrees:commitDiff',
  worktreesFullDiff: 'worktrees:fullDiff',
  worktreesRemove: 'worktrees:remove',
  worktreesDeleteRemote: 'worktrees:deleteRemoteBranch',
  worktreesCreate: 'worktrees:create',
  worktreesSync: 'worktrees:sync',
  worktreesRenameBranch: 'worktrees:renameBranch',
  worktreesWorkingFiles: 'worktrees:workingFiles',
  worktreesWorkingFileDiff: 'worktrees:workingFileDiff',
  worktreesCommitFiles: 'worktrees:commitFiles',
  prGet: 'pr:get',
  ghStatus: 'gh:status',
  terminalsAvailable: 'terminals:available',
  terminalsResume: 'terminals:resumeSession',
  terminalsOpenDir: 'terminals:openDir',
  openEditor: 'open:editor',
  openFinder: 'open:finder',
  openUrl: 'open:url',
  pickDirectory: 'dialog:pickDirectory',
  pickApplication: 'dialog:pickApplication',
} as const;
